version: '3'
services:
  caldera:
    image: openbas/caldera-server:5.0.0
    restart: always
    ports:
      - "8888:8888"
    environment:
      CALDERA_URL: http://localhost:8888
    volumes:
      - type: bind
        source: caldera.yml
        target: /usr/src/app/conf/local.yml
  openbas:
    environment:
      [...]
      - INJECTOR_CALDERA_URL=http://caldera:8888
      - INJECTOR_CALDERA_PUBLIC_URL=${CALDERA_PUBLIC_URL}
      - INJECTOR_CALDERA_API_KEY=${CALDERA_API_KEY}