version: '3'
services:
  openbas-dev-caldera:
    container_name: openbas-dev-caldera
    image: openbas/caldera-server:5.1.0
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      CALDERA_URL: http://localhost:8888
    volumes:
      - type: bind
        source: caldera.yml
        target: /usr/src/app/conf/local.yml