version: '3'
services:
  openbas-dev-pgsql:
    container_name: openbas-dev-pgsql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openbas
    ports:
      - "5432:5432"
    restart: unless-stopped
  openbas-dev-minio:
    container_name: openbas-dev-minio
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: unless-stopped
  openbas-dev-rabbitmq:
    container_name: openbas-dev-rabbitmq
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
  openbas-dev-caldera:
    container_name: openbas-dev-caldera
    image: openbas/caldera-server:5.0.0
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      CALDERA_URL: http://localhost:8888
    volumes:
      - type: bind
        source: caldera.yml
        target: /usr/src/app/conf/local.yml